name: Deployment

on:
  push:   
  pull_request:
    types: [closed, assigned, opened, reopened] 


jobs:
  build-push-docker-image:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
     id-token: write
   strategy:
      matrix:
        go-version: [ '1.17' ]
  
   steps:
    - name: Set up Go 
      id: go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    
    - name: checkout repository
      uses: actions/checkout@v3
      
        
   
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into github registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        
        username: syamoliam
        password: Syamoliam143$

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v1
      with: 
        images: syamoliam/githubactions

    - name: Build and Push Docker Image 
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
